trigger:
  - master

pool:
  vmImage: 'windows-2019'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'npm install and build'

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run build'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'stfu'
    sourceFolder: 'dist'
    contents: '**'
    targetFolder: 'caddy/srv'